from .test_responseElement import ResponseElementTest
from .test_recordElement import RecordElementTest
from .test_getDigitsElement import GetDigitsElementTest
from .test_getInputElement import GetInputElementTest
from .test_messageElement import MessageElementTest
