name: UnitTests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    name: UnitTests
    strategy:
      matrix:
        python-version: [ 3.8, 3.9, 3.11]
        os: [macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Dependencies Installation
        run: |
          pip install tox
      - name: Run Tests
        run: |
          python --version
          tox -e py
    
  coverage:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: [3.11]
      steps:  
        - uses: actions/checkout@v2
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
        - name: Display Python version
          run: python -c "import sys; print(sys.version)"
        - name: Dependencies Installation
          run: |
            pip install tox
            pip install coverage
        - name: Run Tests
          run: |
            python --version
            tox -e py
        - name: Upload coverage to Codecov
          uses: codecov/codecov-action@v1
          with:
            flags: unittests
